
theme: jekyll-theme-hacker

repository: CompilerFrontiers/CompilerFrontiers.github.io
title: Compiler Frontiers Workshop
author: Nicolas Bohm Agostini

# --- List of links in the navigation bar --- #

navbar-links:
  Program: "pages/2023/detailed_program_2023"
  Call for Papers: "pages/2023/call_for_papers_2023"
  CFW's home: "https://compilerfrontiers.github.io/"

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

# plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
