
theme: jekyll-theme-hacker

title: Compiler Frontiers Workshop
author: Nicolas Bohm Agostini

# --- List of links in the navigation bar --- #

navbar-links:
  Call for Papers: "call_for_papers_2022"
  Program: "program_2022"
  CFW's home: "https://compilerfrontiers.github.io/"

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"


site-css:
 - "/assets/css/cfw.css"